name: ascii Generate ASCii Artwork

on: push

jobs:
  build_job_1:
    runs-on: ubuntu-latest
    steps:
    - name: Install cowsay program
      run: sudo apt-get install cowsay -y

    - name: Execute cowsay CMD
      run: cowsay -f ghostbusters "Run for cover I am a ghost yum yum" >> ghost.txt

    - name: sleep for 30 seconds
      run: sleep 30

  test_job_2:
    runs-on: ubuntu-latest
    steps:
    - name: sleep for 10 seconds
      run: sleep 10

    - name: test file exists
      run: grep -i "ghost" ghost.txt

  deploy_job_3:
    runs-on: ubuntu-latest
    steps:  
    - name: Read file
      run: cat beefburger.txt

    - name: deploy
      run: echo deploying.......