name: Generate ASCii Artwork

on: push

jobs:
  ascii_job:
    runs-on: ubuntu-latest
    steps:
    - name: checkout Repo
      uses: actions/checkout@v4

    - name: Install cowsay program
      run: sudo apt-get install cowsay -y

    - name: Execute cowsay CMD
      run: cowsay -f boy "Run for cover I am a cow ----RAWR" >> dragon.txt

    - name: test file exists
      run: grep -i "cow" dragon.txt

    - name: Read file
      run: cat dragon.txt

    - name: list repo files
      run: ls -ltra